### ISSUE TITLE
Change notation

### ISSUE THREAD

**Issue by DayS** [JoanZapata/string-format#1]
You should provide a way to change the notation for placeholders. I was thinking about this a method like this in the builder : `placeholder(String prefix, String suffix)`.

So, an example with json may become something like this :

``` java
String query = Strings.format(
            "{" +
            "  'firstName': '%firstname%'," + 
            "  'lastName': '%lastname%'," +
            "  'age': %age%" +
            "}")
            .with("firstname", "John")
            .with("lastname", "Smith")
            .with("age", "25")
            .placeholder("%", "%")
            .make();
```

**Comment by JoanZapata** [comment]
Thanks for posting an issue.
It would be nice indeed. I'll work on this ASAP!
