### ISSUE TITLE
unnamed placeholders

### ISSUE THREAD

**Issue by hexmind** [JoanZapata/string-format#3]
What do you think about alternative unnamed placeholders feature?
```
Strings.format("Hello {} {}!")
	.build("John", "Doe"); // varargs
```

**Comment by JoanZapata** [comment]
Thanks for your suggestion.

I think this is really close to what `String.format` does.

```java
String.format("Hello %s %s!", "John", "Doe");
```

The purpose of this lib is to manage names placeholders.
